version: "3.3"
services:
  serve:
    build:
      context: .
      dockerfile: lt-stress-serve.Dockerfile
    image: aleksas/lt-stress-serve:0.0.2
    expose:
      - "8500"
      - "8501"
  query:
    build:
      context: .
      dockerfile: lt-stress-query.Dockerfile
      args:
        - MODEL_SERVER_ADDRESS=serve:8500
    image: aleksas/lt-stress-query:0.0.2
    depends_on:
      - serve
    expose:
      - "5000"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - query
    ports:
      - 8080:5000